<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\SilverbridgeWeb.Common.Presentation\SilverbridgeWeb.Common.Presentation.csproj" />
    <ProjectReference Include="..\SilverbridgeWeb.Modules.News.Application\SilverbridgeWeb.Modules.News.Application.csproj" />
    <ProjectReference Include="..\SilverbridgeWeb.Modules.News.Domain\SilverbridgeWeb.Modules.News.Domain.csproj" />
  </ItemGroup>
</Project>
