// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SilverbridgeWeb.Modules.News.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddArticleAuthorName : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "author_first_name",
                schema: "news",
                table: "articles",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "author_last_name",
                schema: "news",
                table: "articles",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "author_first_name",
                schema: "news",
                table: "articles");

            migrationBuilder.DropColumn(
                name: "author_last_name",
                schema: "news",
                table: "articles");
        }
    }
}
