// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SilverbridgeWeb.Modules.News.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddArticleTypeAndMatchReportDetails : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "article_type",
                schema: "news",
                table: "articles",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "match_report_details",
                schema: "news",
                columns: table => new
                {
                    article_id = table.Column<Guid>(type: "uuid", nullable: false),
                    home_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    away_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    home_goals = table.Column<int>(type: "integer", nullable: false),
                    home_points = table.Column<int>(type: "integer", nullable: false),
                    away_goals = table.Column<int>(type: "integer", nullable: false),
                    away_points = table.Column<int>(type: "integer", nullable: false),
                    competition = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    venue = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    match_date_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_match_report_details", x => x.article_id);
                    table.ForeignKey(
                        name: "fk_match_report_details_articles_article_id",
                        column: x => x.article_id,
                        principalSchema: "news",
                        principalTable: "articles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "match_report_details",
                schema: "news");

            migrationBuilder.DropColumn(
                name: "article_type",
                schema: "news",
                table: "articles");
        }
    }
}
