name: CI Build and Test on Pull Request

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.x.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName!~SilverbridgeWeb.WebUI.BrowserTests"

      - name: Install Playwright browser
        shell: pwsh
        run: src/Frontend/test/SilverbridgeWeb.WebUI.BrowserTests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

      - name: Run browser tests
        run: dotnet test src/Frontend/test/SilverbridgeWeb.WebUI.BrowserTests/SilverbridgeWeb.WebUI.BrowserTests.csproj --no-build --configuration Release --verbosity normal
